apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: <APP_NAME>
  namespace: <APP_NAME>
spec: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: <APP_NAME>
  name: <APP_NAME>
spec:
  containers:
  - image: <APP_IMAGE>
    name: <APP_NAME>
    securityContext:
      allowPrivilegeEscalation: false
    # Assumption - it is a batch job; it will take many resources
    # Assumption - it doesn't have a port, just a one off thing
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "3Gi"
        cpu: "2"
  dnsPolicy: ClusterFirst
  restartPolicy: Never