apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: <APP_NAME>
  namespace: <APP_NAME>
  labels:
    app: <APP_NAME>
spec:
  selector:
    matchLabels:
      app: <APP_NAME>
  endpoints:
  - port: http