apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: go-server
  namespace: go-server
  labels:
    app: go-server
spec:
  selector:
    matchLabels:
      app: go-server
  endpoints:
  - port: http