apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: go-server
  namespace: go-server
spec: {}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-resource-constraint
  namespace: go-server
spec:
  limits:
  - default: # this section defines default limits
      cpu: "500m"
      memory: "128Mi"
    defaultRequest: 
      cpu: "250m"
      memory: "64Mi"
    max: 
      cpu: "1"
      memory: "800Mi"
    min:
      cpu: "100m"
      memory: "100Mi"
    type: Container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: go-server
  name: go-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-server
    spec:
      serviceAccountName: go-server
      containers:
      - image: <APP_IMAGE>
        name: go-server
        command: ["./go-server"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-server
  name: go-server
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: go-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: go-server
